config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'highlights#index'
  
	get '/highlights', to: 'highlights#new'
  post '/highlights', to: 'highlights#create'
  resources :highlights, only: [:index, :show] do
    resources :likes, only: [:create, :destroy]
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/signup', to: 'users#destroy'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :highlights
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :highlights

	# book_id : int
	# title : string
	# subtitle : string
	# author : string
	# genre : string
	# published_date : datetime
	# description : text

	validates :title, uniqueness: true 

	# TO DO :https://www.googleapis.com/books/v1/volumes?q=title:...&author:.....
	def self.create_from_book_title(book_title)

		# require 'uri'
		book_q_param = URI.encode_www_form({ q:book_title})
		# ex.) params = URI.encode_www_form({ q: 'こうすれば必ず人は動く'})

		# google book api
		uri = URI.parse("https://www.googleapis.com/books/v1/volumes?#{book_q_param}")
		books_json = Net::HTTP.get(uri)
    books_param = JSON.parse(books_json)

    top_book_param = books_param["items"][0]["volumeInfo"]

    new_book = self.new
		new_book.title = top_book_param['title']
		new_book.subtitle = top_book_param['subtitle']
		new_book.author = top_book_param['authors']
		new_book.genre = nil
		new_book.published_date = top_book_param['publishedDate']
		new_book.description = top_book_param['description']
		new_book.save
  end

end

app/models/highlight.rb
class Highlight < ApplicationRecord
	belongs_to :book
	belongs_to :user
	has_many :likes
	#自分にlikeしたユーザを複数持つ
	has_many :liked_users, through: :likes, source: :user

	validates :content, uniqueness: true 

		def self.create_from_highlights_text(highlights_text)
  	# new_highlight = self.new
		# new_highlight.content = highlight_text
		# new_highlight.save

		split_txt = highlights_text.delete(' ').split(' ')
		book_title = split_txt[1]
		book_author = split_txt[2]

		Book.create_from_book_title(book_title)
		book = Book.find_by(title: book_title)

		split_txt.each.with_index do |txt, idx|
			if txt.include?('色のハイライト') then
				new_highlight = self.new
				new_highlight.content = split_txt[idx+1]
				new_highlight.book_id = book.id
			  new_highlight.save
			end
		end

  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :highlight
  belongs_to :user
  
  validates_uniqueness_of :highlight_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
   before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  
  mount_uploader :image, ImageUploader
  
  has_many :highlights, dependent: :destroy
  has_many :likes, dependent: :destroy
  # likeしたhighlightを複数持つ
  has_many :liked_highlights, through: :likes, source: :highlight
  
  
  def already_liked?(highlight)
    self.likes.exists?(highlight_id: highlight.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    # userのbookだけ表示？
    @books = Book.all
  end

  def show
    @book = @book.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  def index
  end

  def show
    @highlight = Highlight.find(params[:id])
    @like = Like.new()
  end

  def new
  end

  def create
    @highlights_text = params['highlights_text']

    Highlight.create_from_highlights_text(@highlights_text)

  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @highlight = Highlight.find(params[:highlight_id])
    
    @like = Like.new(
      highlight_id: params[:highlight_id],
      user_id: current_user.id
    )
    
    if @like.save
      redirect_to highlight_path(@highlight)
    else
      render template: 'highlights/show'
    end
  end
  
  def destroy
    @like = Like.find_by(highlight_id: params[:highlight_id], user_id: current_user.id)
    @like.destroy
    redirect_to highlihgt_path(params[:highlight_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "ログインに失敗しました。もう一度お試しください。"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "アカウントの作成に成功しました！"
      redirect_to @user
    else
      flash.now[:danger] = "入力が間違っています。もう一度お試しください。"
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<% @books.each do |book|%>
	<div>
	  <%= book.image %>
	  <%= book.title %>
	  <%= book.subtitle%>
	  <%= book.genre %>
	  <%= book.author %>
	</div>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div>
  <%= @book.image %>
  <%= @book.title %>
  <%= @book.subtitle%>
  <%= @book.genre %>
  <%= @book.published_date %>
  <%= @book.author %>
  <%= @book.description %>
</div>

app/views/highlights/create.html.erb
<h4>以下のハイライトが更新されました。</h4>

<% split_list = @highlights_text.delete(' ').split(' ') %>
<%= 'title: ' + split_list[1] %><br>
<%= 'author: ' + split_list[2] %><br>
<% split_list.each.with_index do |txt, idx| %>
	<% if txt.include?('色のハイライト') then %>
	  <% highlight_flag = true %>
	  ハイライト:
	  <%= split_list[idx+1] %><br>
	  <% next %>
	<% end %>
<% end %>

app/views/highlights/edit.html.erb
<h1>Highlights#edit</h1>
<p>Find me in app/views/highlights/edit.html.erb</p>

app/views/highlights/index.html.erb
<h1>Highlights#index</h1>
<p>Find me in app/views/highlights/index.html.erb</p>

app/views/highlights/new.html.erb
<%= form_tag({controller: :highlights, action: :create}, {method: :post}) do %>
  <div><%= text_area_tag :highlights_text, 'ハイライト', :size=>"100x50" %></div>
  <%= submit_tag "作成" %>
<% end %>

app/views/highlights/show.html.erb
<div>
  <div class="userimg"><img src="#" alt="user-image"></div>
  
  <div>
    <p>本文</p>
    <p><%= @highlight.content %></p>
  </div>
  
  <h3>いいね件数: <%= @highlight.likes.count %></h3>
  
  
  <% if current_user.already_liked?(@highlight) %>
    <%= button_to "いいねを取り消す",  highlight_like_path(@highlight), method: :delete %>
  <% else %>
    <%= form_for [@highlight, @like] do %>
      <% if @like.errors.any? %>
        <% @like.errors.full_messages.each do |msg| %>
          <li style="color: red"><%= msg %></li>
        <% end %>
      <% end %>
    
      <%= f.submit "いいね！" %>
    <% end %>
  <% end %>
  
  <h3>この記事にいいねしたユーザ</h3>
  <% @highlight.liked_users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%#= link_to "About", about_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KindleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      以下のエラーが見つかりました。
    </div>
    
    <ul>
      <%= @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>


<%= form_for(:user, url: signup_path) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%=f.label :image,"ユーザー画像" %>
    <%= f.file_field :image %>
  </div>
  
  <%= f.submit "Create Account", class: "btn btn-primary" %>
  
<% end %>

app/views/users/new.html.erb
<%= form_for(:user, url: signup_path) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :image,"ユーザー画像" %>
    <%= f.file_field :image %>
  </div>
  
  <%= f.submit "Create Account", class: "btn btn-primary" %>
  
<% end %>

app/views/users/show.html.erb
<div>
  <%= @user.image %>
  <%= @user.name %>
  <%= @user.email %>
</div>